### ISSUE TITLE
Crashing Glyphs

### ISSUE THREAD

**Issue by kosbarts** [AlphabetType/MasterSelector#3]
Version 2.6.5 (1330)

Every time I install the plugin Glyphs refuses to start and crashes.

**Comment by arialcrime** [comment]
I can’t reproduce this, it does work fine in 1330 and previous versions for me. Also de- and reinstalling does not cause a crash. Are you installing it through GlyphsApp’s Plugin Manager? Is this also happening with other plugins? Have you sent the crash report to @schriftgestalt so they can have a look?

**Comment by kosbarts** [comment]
I was using the Plugin Manager and I was installing plugins one at a time. Every time I installed MasterSelector Glyphs refused to open (not even showing the crash report window).

Now I tried again and it did work. Honestly I have no clue... Consider the issue closed.
